# config/database.yml
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# 生产环境使用 PostgreSQL
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  database: <%= ENV.fetch("DB_NAME") { "teddy1_production" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "teddy1" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "asdflkjqwerpoiu" } %>